runtime: java17
env_variables:
  JAVA_HOME: '/usr/lib/jvm/java-1.7.0-openjdk-amd64'

instance_class: F1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
